import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const montserrat = localFont({
  src: '../../public/Montserrat.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
